spring.application.name: captain
server:
  port: 22000
  servlet.context-path: /captain

eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://cat:20001/shield/eureka,http://dog:20002/shield/eureka
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true
ribbon:
  eager-load:
    clients: captain
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream'
